---
vagrantfile-local:
    vm:
        box: VagrantWebdev
        box_url: 'http://static.fresh-team.ru/vagrant/debian-wheezy-i386.box'
        hostname: null
        network:
            private_network: 192.168.3.10
            forwarded_port:
                xVuFWvEA5kBD:
                    host: '5792'
                    guest: '22'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: puphpet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/puphpet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            gvonkvBg2YHZ:
                id: vagrant-root
                source: 'z:/srv'
                target: /var/www
                nfs: 'false'
        usable_port_range: 2200..2250
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
