---
vagrantfile-local:
    vm:
        box: VagrantWebdev
        box_url: 'http://static.fresh-team.ru/vagrant/debian-wheezy-i386.box'
        server_ip: 192.168.2.10
        memory: 1024
        provision:
            p1:
                type: shell
                path: provision/shell/initial-setup.sh
            p2:
                path: provision/shell/configure.sh
            # p3:
            #     type: shell
            #     path: provision/shell/runtime.sh
            #     args:
            #         - val1
            #         - o pt1
        synced_folder:
            s1:
                id: vagrant-root
                source: 'z:/srv'
                target: /var/www
                nfs: 'false'
                create: 'true'
                owner: 'www-data'
                group: 'www-data'

# ; SMTP server to send emails
# ; if you change this option, you need to execute vagrant provision
mailcatcher:
    install: 0
    settings: 
        smtp_host: smtp.mail.ru
        smtp_port: 465
        smtp_user: test@mail.ru
        smtp_password: 
        smtp_sender: test@mail.ru