---
vagrantfile-local:
    vm:
        box: fobia-debian-wheezy
        box_url: 'https://vagrantcloud.com/fobia/debian-wheezy/version/1/provider/virtualbox.box'
        # vagrant init phalconbox https://s3-eu-west-1.amazonaws.com/phalcon/phalcon125-apache2-php54-mysql55.box
        server_ip: 192.168.2.10
        memory: 1024
        provision:
            p1:
                type: shell
                path: provision/scripts/install.sh
            p2:
                type: shell
                path: provision/scripts/install-pear.sh
            p3:
                type: shell
                path: provision/scripts/install-php-dev-tools.sh
            p4:
                type: shell
                path: provision/scripts/install-java.sh
            p5:
                type: shell
                path: provision/scripts/install-nodejs.sh
            p6:
                type: shell
                path: provision/data/configure.sh
                args:
                    - apache2 dnsmasq memcached mysql php postgresql redis sphinx
                    - vim
            #         - o pt1
        synced_folder:
            s1:
                id: vagrant-root
                source: 'z:/srv'
                target: /var/www
                nfs: 'false'
                create: 'true'
                owner: 'www-data'
                group: 'www-data'

    ssh:
        host: null
        port: null
        # private_key_path: provision/data/insecure_private_key
        username: null
        guest_port: null
        keep_alive: true
        forward_agent: true
        forward_x11: true
        shell: 'bash -l'
    vagrant:
        host: detect
# ; SMTP server to send emails
# ; if you change this option, you need to execute vagrant provision
mailcatcher:
    install: 0
    settings: 
        smtp_host: smtp.mail.ru
        smtp_port: 465
        smtp_user: test@mail.ru
        smtp_password: 
        smtp_sender: test@mail.ru